US 01.05.01 Create view for saved ingredients #7
CMPUT301F22T32/Happy-Meals pull request #32
Opened 2022-10-26 17:48 UTC by kstark1

Included basic functionality for viewing ingredients list. Does not have interaction with the database yet.

2022-10-27 16:47 UTC, sruduke commented
Approved

2022-10-29 15:07 UTC, jeastgaard requested changes
We should not have files dedicated to small enumerations. A single constants file should be more than sufficient for this project.

2022-10-29 15:07 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/AmountUnit.java
> +public enum AmountUnit {
Why do we have an entire file dedicated to an enum?

2022-10-29 15:07 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/Ingredient.java
> +    public Ingredient(String description, String bestBeforeDate, Location location, Integer amount, AmountUnit unit, IngredientCategory category) {
Need an empty constructor as well for database serialization.

2022-10-29 15:07 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/IngredientCategory.java
> +public enum IngredientCategory {
Enum file? Should we not be putting everything into a constants file?

2022-10-29 15:07 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/Location.java
> +public enum Location {
Enum File?

2022-10-29 15:07 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/MainActivity.java
> +        Intent intent = new Intent(getApplicationContext(), IngredientStorageActivity.class);
Debug code should be removed for pull.

2022-11-01 19:48 UTC, jeastgaard approved these changes

2022-11-01 22:37 UTC, merged