28 create login page
CMPUT301F22T32/Happy-Meals pull request #33
Opened 2022-10-27 16:49 UTC by sruduke

Base implementation of login page and main home page (entry point for navigation).

2022-10-28 02:32 UTC, jeastgaard requested changes
Mostly styling that needs to be changed and possibly class names. I wonder about the need for an array adapter for the main list on the main menu.

2022-10-28 02:32 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/LoginScreen.java
> +public class LoginScreen extends AppCompatActivity {
If this is an activity then the class name should reflect that.

2022-10-28 02:32 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/LoginScreen.java
> +        TextView forgetPassword = findViewById(R.id.forgot_password);
Variable name "forgetPassword" should be "forgotPassoword" I think?

2022-10-28 02:32 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/LoginScreen.java
> +    protected void onCreate(Bundle savedInstanceState) {
Overall styling, make sure to add the spaces between <, {, (, etc.

2022-10-28 02:32 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/MainActivity.java
> +        ListView options = findViewById(R.id.option_list);
Styling spacing

2022-10-28 02:32 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/MainActivityListAdapter.java
> +public class MainActivityListAdapter extends ArrayAdapter<String> {
MainActivityListAdapter, I think the name should reflect what the adapter is for. Such as optionsListAdapter etc.

2022-10-28 02:32 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/MainActivity.java
> +        ListView options = findViewById(R.id.option_list);
Why are we using an adapter for the options?

2022-10-28 02:32 UTC, jeastgaard commented on app/src/main/java/com/example/happymeals/MainActivityListAdapter.java
> +        View view = convertView;
This is redundant, should just use the convertView

2022-11-01 23:08 UTC, kstark1 approved these changes

2022-11-01 23:48 UTC, jeastgaard approved these changes

2022-11-01 23:50 UTC, merged